In [1]:
#Key Changes: Remove Outliers, mULTICOLLEAnirity treatment, Log convert of target, Grid Search GBM, Loop in final gbm for best score

import pandas as pd
import matplotlib.pyplot as plt

from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import Imputer
from sklearn import linear_model
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestRegressor


import datetime
from datetime import timedelta
import numpy as np
import gc 
gc.collect()
import plotly_express as px
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.simplefilter(action='ignore')
import os

pd.set_option('display.max_columns', 100)

In [18]:
#Download data
os.chdir('/local/home/rvshnkr/kaggle_data/Home_Credit/')
# import os
#Uncomment Below lines to download data from Kaggle and Unzip it in Directory
# os.environ['KAGGLE_USERNAME'] = "raviYYYYXXX" 
# os.environ['KAGGLE_KEY'] = "XXXXXX"
# !kaggle competitions download -c home-credit-default-risk 
# !unzip "*.zip"

Warning: Looks like you're using an outdated API Version, please consider updating (server 1.5.6 / client 1.5.4)
Downloading sample_submission.csv.zip to /local/home/rvshnkr/kaggle_data/Home_Credit
  0%|                                                | 0.00/117k [00:00<?, ?B/s]
100%|████████████████████████████████████████| 117k/117k [00:00<00:00, 35.6MB/s]
Downloading application_test.csv.zip to /local/home/rvshnkr/kaggle_data/Home_Credit
  0%|                                               | 0.00/5.81M [00:00<?, ?B/s]
100%|██████████████████████████████████████| 5.81M/5.81M [00:00<00:00, 85.0MB/s]
Downloading application_train.csv.zip to /local/home/rvshnkr/kaggle_data/Home_Credit
 69%|██████████████████████████▎           | 25.0M/36.1M [00:00<00:00, 47.1MB/s]
100%|██████████████████████████████████████| 36.1M/36.1M [00:00<00:00, 83.6MB/s]
Downloading bureau.csv.zip to /local/home/rvshnkr/kaggle_data/Home_Credit
 90%|██████████████████████████████████    | 33.0M/36.8M [00:00<00:00, 46.1MB/s]
100%|██████████████████████████████████████| 36.8M/36.8M [00:00<00:00, 69.4MB/s]
Downloading bureau_balance.csv.zip to /local/home/rvshnkr/kaggle_data/Home_Credit
 70%|██████████████████████████▊           | 40.0M/56.8M [00:00<00:00, 63.3MB/s]
100%|███████████████████████████████████████| 56.8M/56.8M [00:00<00:00, 104MB/s]
Downloading previous_application.csv.zip to /local/home/rvshnkr/kaggle_data/Home_Credit
 75%|████████████████████████████▍         | 57.0M/76.3M [00:00<00:00, 67.7MB/s]
100%|███████████████████████████████████████| 76.3M/76.3M [00:00<00:00, 102MB/s]
Downloading credit_card_balance.csv.zip to /local/home/rvshnkr/kaggle_data/Home_Credit
 99%|█████████████████████████████████████▋| 96.0M/96.7M [00:01<00:00, 63.4MB/s]
100%|██████████████████████████████████████| 96.7M/96.7M [00:01<00:00, 71.1MB/s]
Downloading POS_CASH_balance.csv.zip to /local/home/rvshnkr/kaggle_data/Home_Credit
 89%|██████████████████████████████████▊    | 97.0M/109M [00:01<00:00, 77.4MB/s]
100%|█████████████████████████████████████████| 109M/109M [00:01<00:00, 100MB/s]
Downloading installments_payments.csv.zip to /local/home/rvshnkr/kaggle_data/Home_Credit
 93%|█████████████████████████████████████   | 251M/271M [00:04<00:00, 61.2MB/s]
100%|████████████████████████████████████████| 271M/271M [00:04<00:00, 60.0MB/s]
Downloading HomeCredit_columns_description.csv to /local/home/rvshnkr/kaggle_data/Home_Credit
  0%|                                               | 0.00/36.5k [00:00<?, ?B/s]
100%|██████████████████████████████████████| 36.5k/36.5k [00:00<00:00, 39.6MB/s]
Archive:  bureau.csv.zip
  inflating: bureau.csv

Archive:  application_train.csv.zip
  inflating: application_train.csv

Archive:  installments_payments.csv.zip
  inflating: installments_payments.csv

Archive:  POS_CASH_balance.csv.zip
  inflating: POS_CASH_balance.csv

Archive:  application_test.csv.zip
  inflating: application_test.csv

Archive:  sample_submission.csv.zip
  inflating: sample_submission.csv

Archive:  credit_card_balance.csv.zip
  inflating: credit_card_balance.csv

Archive:  previous_application.csv.zip
  inflating: previous_application.csv

Archive:  bureau_balance.csv.zip
  inflating: bureau_balance.csv

9 archives were successfully processed.

In [19]:
os.chdir('/local/home/rvshnkr/kaggle_data/Home_Credit/')
train=pd.read_csv('application_train.csv')
test=pd.read_csv('application_test.csv')
display(train.shape,train.head(2),test.shape,test.head(2))

(307511, 122)

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,...,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,351000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.018801,-9461,-637,-3648.0,-2120,NaN,1,1,0,1,1,0,Laborers,1.0,2,2,WEDNESDAY,10,0,0,0,0,0,0,Business Entity Type 3,0.083037,0.262949,0.139376,0.0247,0.0369,0.9722,0.6192,0.0143,0.00,...,0.0250,0.0369,0.9722,0.6243,0.0144,0.00,0.0690,0.0833,0.1250,0.0375,0.0205,0.0193,0.0000,0.00,reg oper account,block of flats,0.0149,"Stone, brick",No,2.0,2.0,2.0,2.0,-1134.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married,House / apartment,0.003541,-16765,-1188,-1186.0,-291,NaN,1,1,0,1,1,0,Core staff,2.0,1,1,MONDAY,11,0,0,0,0,0,0,School,0.311267,0.622246,NaN,0.0959,0.0529,0.9851,0.7960,0.0605,0.08,...,0.0968,0.0529,0.9851,0.7987,0.0608,0.08,0.0345,0.2917,0.3333,0.0132,0.0787,0.0558,0.0039,0.01,reg oper account,block of flats,0.0714,Block,No,1.0,0.0,1.0,0.0,-828.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

(48744, 121)

,SK_ID_CURR,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,...,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100001,Cash loans,F,N,Y,0,135000.0,568800.0,20560.5,450000.0,Unaccompanied,Working,Higher education,Married,House / apartment,0.018850,-19241,-2329,-5170.0,-812,NaN,1,1,0,1,0,1,NaN,2.0,2,2,TUESDAY,18,0,0,0,0,0,0,Kindergarten,0.752614,0.789654,0.159520,0.066,0.059,0.9732,NaN,NaN,NaN,0.1379,...,0.0666,0.059,0.9732,NaN,NaN,NaN,0.1379,0.125,NaN,NaN,NaN,0.0514,NaN,NaN,NaN,block of flats,0.0392,"Stone, brick",No,0.0,0.0,0.0,0.0,-1740.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
1,100005,Cash loans,M,N,Y,0,99000.0,222768.0,17370.0,180000.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.035792,-18064,-4469,-9118.0,-1623,NaN,1,1,0,1,0,0,Low-skill Laborers,2.0,2,2,FRIDAY,9,0,0,0,0,0,0,Self-employed,0.564990,0.291656,0.432962,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0

In [23]:
os.chdir('/local/home/rvshnkr/home_credit_default/')
train[1:100].to_csv('data/train_sample.csv')
test[1:100].to_csv('data/test_sample.csv')

In [25]:
#For Profiling of DataSet to check for missing values, correlations, Histogram, Distributions etc
import pandas_profiling

sample_length=min(len(train),10000)
sample_dataset=train.sample(n=sample_length)

profile = sample_dataset.profile_report(
check_correlation_pearson= False, 
correlations={'pearson': False,
'spearman': False,
'kendall': False,
'phi_k': False,
'cramers': False,
'recoded':False},title='Raw Data Exploration')

In [31]:
profile.to_file(output_file="data/train_data.html")